export function getStrings(lang){
  console.log(lang);
  switch (lang){
    case "es-es":
      return {
        "bpm"       : "bpm",
        "steps"     : "pasos", 
        "kcal"      : "kcal",
        "Steps"     : "Pasos",
        "Distance"  : "Distancia",
        "Floors"    : "Pisos",
        "Active"    : "Activo",
        "Calories"  : "Calorías",
        
        "Today"     : "Today", 
        "Sun"       : "Sun",
        "Mon"       : "Mon",
        "Tues"      : "Tues",
        "Wed"       : "Wed",
        "Thurs"     : "Thurs",
        "Fri"       : "Fri",
        "Sat"       : "Sat",
        "Sunday"    : "Sunday",
        "Monday"    : "Monday",
        "Tuesday"   : "Tuesday",
        "Wednesday" : "Wednesday",
        "Thursday"  : "Thursday",
        "Friday"    : "Friday",
        "Saturday"  : "Saturday",
        "Jan."      : "Jan.",
        "Feb."      : "Feb.",
        "Mar."      : "Mar.",
        "Apr."      : "Apr.",
        "May"       : "May",
        "June"      : "June",
        "July"      : "July",
        "Aug."      : "Aug.",
        "Sept."     : "Sept.",
        "Oct."      : "Oct.",
        "Nov."      : "Nov.",
        "Dec."      : "Dec.",
        "January"   : "January",
        "February"  : "February",
        "March"     : "March",
        "April"     : "April",
        "August"    : "August",
        "September" : "September",
        "October"   : "October",
        "November"  : "November",
        "December"  : "December",
        
        "Tornado"                 : "Tornado",
        "Tropical Storm"          : "Tropical Storm",
        "Hurricane"               : "Hurricane",
        "Severe Thunderstorms"    : "Severe Thunderstorms",
        "Thunderstorms"           : "Thunderstorms",
        "Mixed Rain And Snow"     : "Mixed Rain And Snow",
        "Mixed Rain And Sleet"    : "Mixed Rain And Sleet",
        "Mixed Snow And Sleet"    : "Mixed Snow And Sleet",
        "Freezing Drizzle"        : "Freezing Drizzle",
        "Drizzle"                 : "Drizzle",
        "Freezing Rain"           : "Freezing Rain",
        "Showers"                 : "Showers",
        "Snow Flurries"           : "Snow Flurries",
        "Light Snow Showers"      : "Light Snow Showers",
        "Blowing Snow"            : "Blowing Snow",
        "Snow"                    : "Snow",
        "Hail"                    : "Hail",
        "Sleet"                   : "Sleet",
        "Dust"                    : "Dust",
        "Foggy"                   : "Foggy",
        "Haze"                    : "Haze",
        "Smoky"                   : "Smoky",     
        "Blustery"                : "Blustery",
        "Windy"                   : "Windy",
        "Cold"                    : "Cold",
        "Cloudy"                  : "Cloudy",
        "Mostly Cloudy"           : "Mostly Cloudy",  
        "Partly Cloudy"           : "Partly Cloudy",
        "Clear"                   : "Clear",
        "Sunny"                   : "Sunny",
        "Fair"                    : "Fair",
        "Mixed Rain And Hail"     : "Mixed Rain And Hail",
        "Hot"                     : "Hot",
        "Isolated Thunderstorms"  : "Isolated Thunderstorms",
        "Scattered Thunderstorms" : "Scattered Thunderstorms",
        "Scattered Showers"       : "Scattered Showers",
        "Heavy Snow"              : "Heavy Snow",
        "Scattered Snow Showers"  : "Scattered Snow Showers",
        "Thundershowers"          : "Thundershowers",
        "Snow Showers"            : "Snow Showers",
        "Isolated Thundershowers" : "Isolated Thundershowers",
        
        "North"           : "North",
        "N."              : "N.",
        "East"            : "East",
        "E."              : "E.",
        "South"           : "South",
        "S."              : "S.",
        "West"            : "West",
        "W."              : "W.",
        "And"             : "And",
        "&"               : "&",
        "Mixed"           : "Mixed",
        "Severe"          : "Severe",
        "Bad"             : "Bad",
        "T-Storms"        : "T-Storms",
        "Clouds"          : "Clouds",
        "Isolated"        : "Isolated",
        "Partly"          : "Partly",
        "Scattered"       : "Scattered",
        "Some"            : "Some",
      }
    case "zh-cn":
      return {
        "bpm"       : "bpm",
        "steps"     : "步", 
        "kcal"      : "千卡",
        "Steps"     : "步數",
        "Distance"  : "距離",
        "Floors"    : "樓層數",
        "Active"    : "活動量",
        "Calories"  : "卡路里",
        
        "Today"     : "Today", 
        "Sun"       : "Sun",
        "Mon"       : "Mon",
        "Tues"      : "Tues",
        "Wed"       : "Wed",
        "Thurs"     : "Thurs",
        "Fri"       : "Fri",
        "Sat"       : "Sat",
        "Sunday"    : "Sunday",
        "Monday"    : "Monday",
        "Tuesday"   : "Tuesday",
        "Wednesday" : "Wednesday",
        "Thursday"  : "Thursday",
        "Friday"    : "Friday",
        "Saturday"  : "Saturday",
        "Jan."      : "Jan.",
        "Feb."      : "Feb.",
        "Mar."      : "Mar.",
        "Apr."      : "Apr.",
        "May"       : "May",
        "June"      : "June",
        "July"      : "July",
        "Aug."      : "Aug.",
        "Sept."     : "Sept.",
        "Oct."      : "Oct.",
        "Nov."      : "Nov.",
        "Dec."      : "Dec.",
        "January"   : "January",
        "February"  : "February",
        "March"     : "March",
        "April"     : "April",
        "August"    : "August",
        "September" : "September",
        "October"   : "October",
        "November"  : "November",
        "December"  : "December",
        
        "Tornado"                 : "Tornado",
        "Tropical Storm"          : "Tropical Storm",
        "Hurricane"               : "Hurricane",
        "Severe Thunderstorms"    : "Severe Thunderstorms",
        "Thunderstorms"           : "Thunderstorms",
        "Mixed Rain And Snow"     : "Mixed Rain And Snow",
        "Mixed Rain And Sleet"    : "Mixed Rain And Sleet",
        "Mixed Snow And Sleet"    : "Mixed Snow And Sleet",
        "Freezing Drizzle"        : "Freezing Drizzle",
        "Drizzle"                 : "Drizzle",
        "Freezing Rain"           : "Freezing Rain",
        "Showers"                 : "Showers",
        "Snow Flurries"           : "Snow Flurries",
        "Light Snow Showers"      : "Light Snow Showers",
        "Blowing Snow"            : "Blowing Snow",
        "Snow"                    : "Snow",
        "Hail"                    : "Hail",
        "Sleet"                   : "Sleet",
        "Dust"                    : "Dust",
        "Foggy"                   : "Foggy",
        "Haze"                    : "Haze",
        "Smoky"                   : "Smoky",     
        "Blustery"                : "Blustery",
        "Windy"                   : "Windy",
        "Cold"                    : "Cold",
        "Cloudy"                  : "Cloudy",
        "Mostly Cloudy"           : "Mostly Cloudy",  
        "Partly Cloudy"           : "Partly Cloudy",
        "Clear"                   : "Clear",
        "Sunny"                   : "Sunny",
        "Fair"                    : "Fair",
        "Mixed Rain And Hail"     : "Mixed Rain And Hail",
        "Hot"                     : "Hot",
        "Isolated Thunderstorms"  : "Isolated Thunderstorms",
        "Scattered Thunderstorms" : "Scattered Thunderstorms",
        "Scattered Showers"       : "Scattered Showers",
        "Heavy Snow"              : "Heavy Snow",
        "Scattered Snow Showers"  : "Scattered Snow Showers",
        "Thundershowers"          : "Thundershowers",
        "Snow Showers"            : "Snow Showers",
        "Isolated Thundershowers" : "Isolated Thundershowers",
        
        "North"           : "North",
        "N."              : "N.",
        "East"            : "East",
        "E."              : "E.",
        "South"           : "South",
        "S."              : "S.",
        "West"            : "West",
        "W."              : "W.",
        "And"             : "And",
        "&"               : "&",
        "Mixed"           : "Mixed",
        "Severe"          : "Severe",
        "Bad"             : "Bad",
        "T-Storms"        : "T-Storms",
        "Clouds"          : "Clouds",
        "Isolated"        : "Isolated",
        "Partly"          : "Partly",
        "Scattered"       : "Scattered",
        "Some"            : "Some",
      }
    default:
      return {
        "bpm"       : "bpm",
        "steps"     : "steps", 
        "kcal"      : "kcal",
        "Steps"     : "Steps",
        "Distance"  : "Distance",
        "Floors"    : "Floors",
        "Active"    : "Active",
        "Calories"  : "Calories",
        
        "Today"     : "Today", 
        "Sun"       : "Sun",
        "Mon"       : "Mon",
        "Tues"      : "Tues",
        "Wed"       : "Wed",
        "Thurs"     : "Thurs",
        "Fri"       : "Fri",
        "Sat"       : "Sat",
        "Sunday"    : "Sunday",
        "Monday"    : "Monday",
        "Tuesday"   : "Tuesday",
        "Wednesday" : "Wednesday",
        "Thursday"  : "Thursday",
        "Friday"    : "Friday",
        "Saturday"  : "Saturday",
        "Jan."      : "Jan.",
        "Feb."      : "Feb.",
        "Mar."      : "Mar.",
        "Apr."      : "Apr.",
        "May"       : "May",
        "June"      : "June",
        "July"      : "July",
        "Aug."      : "Aug.",
        "Sept."     : "Sept.",
        "Oct."      : "Oct.",
        "Nov."      : "Nov.",
        "Dec."      : "Dec.",
        "January"   : "January",
        "February"  : "February",
        "March"     : "March",
        "April"     : "April",
        "August"    : "August",
        "September" : "September",
        "October"   : "October",
        "November"  : "November",
        "December"  : "December",
        
        "Tornado"                 : "Tornado",
        "Tropical Storm"          : "Tropical Storm",
        "Hurricane"               : "Hurricane",
        "Severe Thunderstorms"    : "Severe Thunderstorms",
        "Thunderstorms"           : "Thunderstorms",
        "Mixed Rain And Snow"     : "Mixed Rain And Snow",
        "Mixed Rain And Sleet"    : "Mixed Rain And Sleet",
        "Mixed Snow And Sleet"    : "Mixed Snow And Sleet",
        "Freezing Drizzle"        : "Freezing Drizzle",
        "Drizzle"                 : "Drizzle",
        "Freezing Rain"           : "Freezing Rain",
        "Showers"                 : "Showers",
        "Snow Flurries"           : "Snow Flurries",
        "Light Snow Showers"      : "Light Snow Showers",
        "Blowing Snow"            : "Blowing Snow",
        "Snow"                    : "Snow",
        "Hail"                    : "Hail",
        "Sleet"                   : "Sleet",
        "Dust"                    : "Dust",
        "Foggy"                   : "Foggy",
        "Haze"                    : "Haze",
        "Smoky"                   : "Smoky",     
        "Blustery"                : "Blustery",
        "Windy"                   : "Windy",
        "Cold"                    : "Cold",
        "Cloudy"                  : "Cloudy",
        "Mostly Cloudy"           : "Mostly Cloudy",  
        "Partly Cloudy"           : "Partly Cloudy",
        "Clear"                   : "Clear",
        "Sunny"                   : "Sunny",
        "Fair"                    : "Fair",
        "Mixed Rain And Hail"     : "Mixed Rain And Hail",
        "Hot"                     : "Hot",
        "Isolated Thunderstorms"  : "Isolated Thunderstorms",
        "Scattered Thunderstorms" : "Scattered Thunderstorms",
        "Scattered Showers"       : "Scattered Showers",
        "Heavy Snow"              : "Heavy Snow",
        "Scattered Snow Showers"  : "Scattered Snow Showers",
        "Thundershowers"          : "Thundershowers",
        "Snow Showers"            : "Snow Showers",
        "Isolated Thundershowers" : "Isolated Thundershowers",
        
        "North"           : "North",
        "N."              : "N.",
        "East"            : "East",
        "E."              : "E.",
        "South"           : "South",
        "S."              : "S.",
        "West"            : "West",
        "W."              : "W.",
        "And"             : "And",
        "&"               : "&",
        "Mixed"           : "Mixed",
        "Severe"          : "Severe",
        "Bad"             : "Bad",
        "T-Storms"        : "T-Storms",
        "Clouds"          : "Clouds",
        "Isolated"        : "Isolated",
        "Partly"          : "Partly",
        "Scattered"       : "Scattered",
        "Some"            : "Some",
        
      }
  }
}